# Trigger on any push to main
trigger:
  - main

pr: none

pool:
  vmImage: ubuntu-20.04

variables:
- group: "Build"

stages:
  - stage: Build
    displayName: Build and push ECR image
    jobs:
      - job: Pulumi
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: 12.20.1
          displayName: 'Install Node.js version 12.20.1'
        - task: Bash@3
          name: npmInstall
          displayName: NPM Install
          inputs:
              targetType: 'inline'
              script: npm i
        - task: Bash@3
          name: pulumiLogin
          displayName: Pulumi Login
          inputs:
              targetType: 'inline'
              script: pulumi login
          env:
            PULUMI_ACCESS_TOKEN: $(PULUMI_ACCESS_TOKEN)
        - task: Bash@3
          name: pulumiStackInit
          displayName: Pulumi Stack Init
          continueOnError: true
          inputs:
              targetType: 'inline'
              script: pulumi stack init dev -v 3 --non-interactive
        - task: Bash@3
          name: pulumiStackSelect
          displayName: Pulumi Stack Select
          inputs:
              targetType: 'inline'
              script: pulumi stack select dev
        - task: Bash@3
          name: pulumiUp
          displayName: Pulumi Up
          inputs:
              targetType: 'inline'
              script: pulumi up -y
